require("mute.plugins-setup")

require("mute.plugins.lsp.lsp-zero")
require("mute.plugins.lsp.nvim-cmp")
require("mute.plugins.lsp.lspsaga")
require("mute.plugins.lsp.lsp-signature")
require("mute.plugins.lsp.mason")

require("mute.plugins.alpha")
require("mute.plugins.autopairs")
require("mute.plugins.auto-session")
require("mute.plugins.indent-blankline")
require("mute.plugins.lualine")
require("mute.plugins.nvim-tree")
require("mute.plugins.telescope")
require("mute.plugins.treesitter")
require("mute.plugins.undotree")

require("mute.core.set")
require("mute.core.remap")
require("mute.core.colorscheme")
